title: Yiteng Mao
email: mao85@wisc.edu
description: >-
  Methodology-Driven AI Researcher. <br>
  Focusing on Post-Training Paradigms, Hallucination Awareness, and Internalizing Consciousness in LLMs.
baseurl: ""
url: "https://RicharMd.github.io"
twitter_username: 
github_username:  RicharMd

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Academic / Professional Settings
show_downloads: false
google_analytics:
